### ISSUE TITLE
Emotion and sentiment-levels features

### ISSUE THREAD

**Issue by philipkb2** [framingeinstein/node-alchemy#19]
Comparing the AlchemyAPI docs with the features list in the alchemy-api node package I see a few features missing. Emotion analysis is a new feature, and sentiment analysis can also be done on the following levels: entity, keyword, and directional. I just wanted to make a request that these features be added. It'd be a big help and I really appreciate the work already done!

Here are links to each feature:
Emotion: http://www.alchemyapi.com/api/emotion-analysis
Entity: http://www.alchemyapi.com/api/entity/sentiment.html
Keyword: http://www.alchemyapi.com/api/keyword/sentiment.html
Directional: http://www.alchemyapi.com/api/relation/sentiment.html

**Comment by framingeinstein** [comment]
@philipkb2,

The documentation has not been updated for emotions and is not specific as to sentiment extraction in entity, keyword, and directional.  I will update the docs as soon as possible.

Emotions were added in the last pull request accepted and can be called in a similar manner as all the rest of the endpoints.

```
alchemy.emotions('<URL|HTML|TEXT>', {}, function(error, response) {
	if (err) throw err;
        // Do something with response
 });
```

To extract sentiment for other calls where it is supported you can do the following:
```
alchemy.entities('<URL|HTML|TEXT>', {'sentiment':1}, function(err, response) {
  if (err) throw err;

  // See http://www.alchemyapi.com/api/entity/htmlc.html for format of returned object
  var entities = response.entities;

  // Do something with data
});
```
Anything passed in the second argument, "{}" by default, is passed on to the api for enabling features and other options.

Thanks,
Jason

**Comment by framingeinstein** [comment]
Docs have been updated.
